// <auto-generated />
using System;
using Meetekat.WebApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Meetekat.WebApi.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220425063715_AddMeetupsUsersRefreshTokensGuestsMeetups")]
    partial class AddMeetupsUsersRefreshTokensGuestsMeetups
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuestMeetup", b =>
                {
                    b.Property<Guid>("meetup_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("guest_id")
                        .HasColumnType("uuid");

                    b.HasKey("meetup_id", "guest_id")
                        .HasName("pk_meetups_users_signups");

                    b.HasIndex("guest_id")
                        .HasDatabaseName("ix_meetups_users_signups_guest_id");

                    b.ToTable("meetups_users_signups", (string)null);
                });

            modelBuilder.Entity("Meetekat.WebApi.Entities.Meetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_meetups");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("ix_meetups_organizer_id");

                    b.ToTable("meetups", (string)null);
                });

            modelBuilder.Entity("Meetekat.WebApi.Entities.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Meetekat.WebApi.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("role").HasValue("User");
                });

            modelBuilder.Entity("Meetekat.WebApi.Entities.Users.Guest", b =>
                {
                    b.HasBaseType("Meetekat.WebApi.Entities.Users.User");

                    b.HasDiscriminator().HasValue("Guest");
                });

            modelBuilder.Entity("Meetekat.WebApi.Entities.Users.Organizer", b =>
                {
                    b.HasBaseType("Meetekat.WebApi.Entities.Users.User");

                    b.HasDiscriminator().HasValue("Organizer");
                });

            modelBuilder.Entity("GuestMeetup", b =>
                {
                    b.HasOne("Meetekat.WebApi.Entities.Users.Guest", null)
                        .WithMany()
                        .HasForeignKey("guest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_meetups_users_signups_guest_id");

                    b.HasOne("Meetekat.WebApi.Entities.Meetup", null)
                        .WithMany()
                        .HasForeignKey("meetup_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meetups_meetups_users_signups_meetup_id");
                });

            modelBuilder.Entity("Meetekat.WebApi.Entities.Meetup", b =>
                {
                    b.HasOne("Meetekat.WebApi.Entities.Users.Organizer", "Organizer")
                        .WithMany("OrganizedMeetups")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organizers_meetups_organizer_id");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Meetekat.WebApi.Entities.Users.RefreshToken", b =>
                {
                    b.HasOne("Meetekat.WebApi.Entities.Users.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_refresh_tokens_user_id");
                });

            modelBuilder.Entity("Meetekat.WebApi.Entities.Users.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Meetekat.WebApi.Entities.Users.Organizer", b =>
                {
                    b.Navigation("OrganizedMeetups");
                });
#pragma warning restore 612, 618
        }
    }
}
